name: cargo build/test/clippy

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        os: [ubuntu-latest, windows-latest, windows-11-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: clippy
      - run: cargo build
      - run: cargo build --release
      - run: cargo test
      - run: cargo clippy
